### ISSUE TITLE
Warning: This plugin slows down Homebridge.

### ISSUE THREAD

**Issue by shayneob** [BlaT2512/homebridge-spanet#6]
I'm running the plugin as a child bridge, and I am getting warnings about the plugin slowing down Homebridge. Also, the child bridge process seems to end and restart frequently. I'm not sure if these issues are related or not
Do you have idea what the issue could be? Thanks for your help.

[1/7/2023, 7:28:20 AM] [homebridge-spanet] This plugin generated a warning from the characteristic 'Target Heater-Cooler State': characteristic was supplied illegal value: number 3 exceeded maximum of 2. See https://homebridge.io/w/JtMGR for more info.
[1/7/2023, 7:28:22 AM] [homebridge-spanet] This plugin slows down Homebridge. The read handler for the characteristic 'Target Temperature' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[1/7/2023, 7:28:22 AM] [homebridge-spanet] This plugin slows down Homebridge. The read handler for the characteristic 'Current Heater-Cooler State' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[1/7/2023, 7:28:22 AM] [homebridge-spanet] This plugin slows down Homebridge. The read handler for the characteristic 'Active' was slow to respond! See https://homebridge.io/w/JtMGR for more info.

[1/7/2023, 7:25:03 AM] [homebridge-spanet] Child bridge process ended
[1/7/2023, 7:25:03 AM] [homebridge-spanet] Process Ended. Code: 1, Signal: null
[1/7/2023, 7:25:10 AM] [homebridge-spanet] Restarting Process...

**Comment by BlaT2512** [comment]
Sorry for very late reply haven't caught up on this library for a while. If you're still interested in using your spa with homebridge you may have noticed that SpaNET transitioned to a newer app and their API is rewritten now. I will be rewriting this library for the new API over next 2 weeks and this should iron out all the bugs and slowness in the plugin right now.

**Comment by shayneob** [comment]
Thanks heaps!!

**Comment by darrendrysdale** [comment]
Thanks for reviewing this. Look forward to an update. Reach out if you need help with testing.

**Comment by BlaT2512** [comment]
@darrendrysdale @shayneob Thanks both for your interest, I will keep in contact over you next few weeks when I get time to finish it off and am ready for testing 👍

**Comment by darrendrysdale** [comment]
Hey Blake @BlaT2512 any progress with the update that you can share?

**Comment by TheTeeDot** [comment]
Hi @BlaT2512, I'll also be keen to test and provide feedback

**Comment by aldobalducci** [comment]
Me tooSent from my iPhoneOn 31 Aug 2023, at 6:52 pm, TheTeeDot ***@***.***> wrote:﻿
Hi @BlaT2512, I'll also be keen to test and provide feedback

**Comment by darrendrysdale** [comment]
Hey @BlaT2512, just checking to see if you have had any success with updating your code to work with the changes to the SpaNet servers.

**Comment by joelhinch** [comment]
@BlaT2512 would really love to get this working with my spa also. let me know if i can contribute in any way.

**Comment by BlaT2512** [comment]
@darrendrysdale @shayneob @joelhinch @aldobalducci @TheTeeDot Apologies for the very long delay, been very busy and hardly on Github the past few months. Have rewritten and just about to publish new version of the library, haven't tested it that much so please feel free to let me know how it works for you and any bugs encountered, feature requests or make pull requests. Cheers

It is not necessary to run the plugin on a child bridge, however due to the SpaNET api rate limit 3 requests per second, when the Home app requests to refresh all the spa accessories it takes a good 5-6 seconds. So if you have lots of other devices on Homebridge, may be a good idea to make it a child bridge still to improve speed.

**Comment by darrendrysdale** [comment]
Sounds great, thanks for looking into this. Happy to share any issues that may pop up. Cheers,DarrenSent from my iPhoneOn 4 Nov 2023, at 6:20 pm, Blake Tourneur ***@***.***> wrote:﻿
@darrendrysdale @shayneob @joelhinch @aldobalducci @TheTeeDot Apologies for the very long delay, been very busy and hardly on Github the past few months. Have rewritten and just about to publish new version of the library, haven't tested it that much so please feel free to let me know how it works for you and any bugs encountered, feature requests or make pull requests. Cheers
It is not necessary to run the plugin on a child bridge, however due to the SpaNET api rate limit 3 requests per second, when the Home app requests to refresh all the spa accessories it takes a good 5-6 seconds. So if you have lots of other devices on Homebridge, may be a good idea to make it a child bridge still to improve speed.

**Comment by darrendrysdale** [comment]
Hey @BlaT2512, have tried loading this and still generating an error. I am using regular username and password which is used for spanet server/app. Is this correct as I know that in previous build you needed it to be encrypted/hash using the other password generator. 

Error I have is as follows which suggests that the details are incorrect but I have rechecked and they are what's used to access app/server. 

4/11/2023, 7:40:32 pmSpa BridgeLoading 1 platforms...
4/11/2023, 7:40:32 pmSpa BridgeBridge is running on port 51836.
4/11/2023, 7:40:32 pmSpa BridgeSpaNETPluginERRORError: Unable to login with details provided. Please ensure that you have the correct username and encrypted password (see Github for details).
4/11/2023, 7:40:32 pmSpa BridgeSpaNETPluginWARNINGWarning: SpaNET plugin inactive. Please address specified issue and reboot Bridge to re-attempt setup.

Suggestions?

**Comment by BlaT2512** [comment]
Hey @darrendrysdale, it appears you are still on the old version as this error message is not in the new version I published. Please ensure you are on version 2.0.0 or update with `npm i -g homebridge-spanet`.

**Comment by darrendrysdale** [comment]
Thanks @BlaT2512 , I was using a HB client and thought it had updated but obviously not. Have tried again and getting this error:
8:28:46 pmWARNINGplugin site unavailable
8:28:47 pmyarn add v1.22.19
8:28:47 pm[1/4] Resolving packages...
8:28:48 pmerror An unexpected error occurred: "https://registry.yarnpkg.com/homebridge-spanet: getaddrinfo EAI_AGAIN registry.yarnpkg.com".
8:28:48 pminfo If you think this is a bug, please open a bug report with the information provided in "/var/lib/hoobs/spabridge/yarn-error.log".
8:28:48 pminfo Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

Possibly it's not accessing the updated version and I can check again tomorrow, wonder if you have thoughts though.

**Comment by BlaT2512** [comment]
This is odd @darrendrysdale , I don't use yarn but just made a folder and tried `yarn add homebridge-spanet` and worked fine. Looks like this is normally a yarn bug or internet/vpn issue or something https://stackoverflow.com/questions/54254121/error-an-unexpected-error-occurred-https-registry-yarnpkg-com-react-getaddr

Maybe try updating through the homebridge online UI, restart, reconnect internet or wait till tomorrow and hopefully fixes itself.

**Comment by darrendrysdale** [comment]
Thanks @BlaT2512. Possibly it's an issue with Hoobs. I'll check tomorrow and if still happening look at another way to install/update. Appreciate your help.

**Comment by BlaT2512** [comment]
No worries @darrendrysdale, let me know how it goes. Can always locally clone the repo if needed.

**Comment by darrendrysdale** [comment]
<img width="1238" alt="Screenshot 2023-11-04 at 10 49 41 pm" src="https://github.com/BlaT2512/homebridge-spanet/assets/69173649/f739d3e3-ed62-4b72-bf60-368effed65ae">
Hey @BlaT2512. I attempted to ssh to hoobs terminal and install the home bridge-spanet package that way but I'm still getting error. Not sure if you can help me find another way to get around this yarn error - you did mention clone but apologies Im not sure how to do that but am willing to try if you can lead me through it

**Comment by shayneob** [comment]
Thanks for the update!

I’ve updated and get “crypto is not defined error”, see below.

***@***.***

**Comment by BlaT2512** [comment]
@shayneob Have fixed this, will push in an update once I fix one other thing in the next couple hours

**Comment by BlaT2512** [comment]
@darrendrysdale This does look correct, strange you are still getting the error. You could try these commands to manually install it:
```
git clone https://github.com/BlaT2512/homebridge-spanet
cd homebridge-spanet
yarn run build
yarn link
```

**Comment by joelhinch** [comment]
Thanks so much for putting in the work here. I am having some trouble setting the Operation Mode: Normal/Away doesnt seem to stick. Just reverts?

**Comment by BlaT2512** [comment]
@joelhinch Yeah same for me going to fix that shortly. Setting a lot of the controls has strange behaviour like the jets turn on when clicked but are stuck saying loading, will work to fix it all. Have also reduced the time for refreshing all the devices now from 6 seconds to 1.

**Comment by joelhinch** [comment]
> @joelhinch Yeah same for me going to fix that shortly. Setting a lot of the controls has strange behaviour like the jets turn on when clicked but are stuck saying loading, will work to fix it all. Have also reduced the time for refreshing all the devices now from 6 seconds to 1.

Awesome! Thanks a heap. 

Do you use home assistant at all? I’ve actually got homebridge paired directly to home assistant so I can use this plugin. Which works well enough. Have you ever consider writing the plugin for HA?

**Comment by BlaT2512** [comment]
@joelhinch I do not use home assistant, however would be open to this. Just quickly googled and appears intergrations are written in Python, doesn't look like it'd be too big an effort to port it over so I will consider this in future.

Also please find fixed operation mode switch in the latest release just published

**Comment by shayneob** [comment]
Hi @BlaT2512 I appear to be getting a bunch of errors, but things seem to work.
![image](https://github.com/BlaT2512/homebridge-spanet/assets/78875384/d871cd41-b8b8-4025-88d5-6be1377ae263)

**Comment by BlaT2512** [comment]
@shayneob Appears still rate limit error happens every now and again which causes these errors, happens for me about every 20th open of the home app. Will try work again on the rate limiting in next release

**Comment by joelhinch** [comment]
> @joelhinch I do not use home assistant, however would be open to this. Just quickly googled and appears intergrations are written in Python, doesn't look like it'd be too big an effort to port it over so I will consider this in future.
> 
> Also please find fixed operation mode switch in the latest release just published

youre an absolute champion! would be amazing to have it direct if you do get around to it one day. i love homekit but have started moving to homeassistant (have been holding off for so long)

**Comment by darrendrysdale** [comment]
Hey Blake @BlaT2512. Managed to install finally however it seems the temp settings for spa are not coming across (unless I am doing something wrong). I have cleared the Homebridge cache and installed a couple of times but result still the same. Is this a known issue or something I need to fix on this end.
Thanks D

 ![image](https://github.com/BlaT2512/homebridge-spanet/assets/69173649/a73db7c1-12ea-48be-a1b1-e07f086ffe3f)

**Comment by joelhinch** [comment]
Hi Blake @BlaT2512 
Is there a way to soecify the power save level? You have on/off but it defaults to low, rather than high when on, (spanet has 3 states for power save, off, low, high). Trying to automate when my spa is allowed to heat. Cheers!

**Comment by BlaT2512** [comment]
Hi @joelhinch , currently you can change whether the switch turns it to low or high by default when switching on in the plugin settings in Homebridge.
However, if you prefer it to be similar to the operation mode with 3 seperate switches for off, low and high let me know.
Cheers

**Comment by joelhinch** [comment]
> Hi @joelhinch , currently you can change whether the switch turns it to low or high by default when switching on in the plugin settings in Homebridge. However, if you prefer it to be similar to the operation mode with 3 seperate switches for off, low and high let me know. Cheers

Thats fantastic @BlaT2512 I missed that, but have found that setting and turned it on. This is great as is, the low setting is kind of irrelevent in most use cases when schedules can accomplish the same thing.

**Comment by joelhinch** [comment]
> Hi @joelhinch , currently you can change whether the switch turns it to low or high by default when switching on in the plugin settings in Homebridge. However, if you prefer it to be similar to the operation mode with 3 seperate switches for off, low and high let me know. Cheers

@BlaT2512 hi mate I have the option ticked but it still seems to switch to Low not High. Are you able to test to see if the behaviour is the same on your end? Thanks!

**Comment by BlaT2512** [comment]
Hi @joelhinch, I was not able to reproduce this bug on my end. The only thing I can think of is that you didn't restart Homebridge after changing the setting, as the plugin loads the config when it first starts up. Try restarting Homebridge and let me know if that works.

**Comment by darrendrysdale** [comment]
Hey Blake @BlaT2512, I have now installed plugin under Hoobs and it brings down all function except the spa temp function. Is this something that others have experienced or is there a way to correct this within the config. Appreciate any support that may help fix this, Cheers.
